language: cpp

sudo: required

dist: trusty

compiler: gcc

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake doxygen groff libsigc++-2.0-dev libgsm1-dev libpopt-dev tcl8.5-dev libgcrypt11-dev libspeex-dev libasound2-dev libopus-dev librtlsdr-dev

before_script:
  - mkdir build
  - cd build

script:
  - cmake ../src
  - cmake --build .
  - cmake --build . --target doc
